/// Deterministic, multilingual fake data for Dart and Flutter applications.
///
/// The package has no Flutter or server dependency. Use [CoFaker] directly in
/// tests, local fixtures, seed scripts, command-line tools, or Flutter apps.
library;

export 'src/clinic.dart';
export 'src/clinic_data.dart';
export 'src/clinic_ops.dart';
export 'src/clinic_texts.dart';
export 'src/co_faker.dart';
export 'src/co_faker_locale.dart';
export 'src/co_faker_locales.dart';
export 'src/coverage.dart';
export 'src/domain.dart';
export 'src/domains.dart';
export 'src/domain_packs/co_fx_domain.dart';
export 'src/domain_packs/co_remit_domain.dart';
export 'src/domain_packs/co_faker_fx.dart';
export 'src/domain_packs/co_faker_remit.dart';
export 'src/domain_packs/co_fake_fx_currency.dart';
export 'src/domain_packs/co_fake_fx_rate_point.dart';
export 'src/domain_packs/co_fake_remit_recipient.dart';
export 'src/domain_packs/co_fake_remittance.dart';
export 'src/domain_packs/co_vet_domain.dart';
export 'src/domain_packs/co_fake_pet.dart';
export 'src/domain_packs/co_faker_vet.dart';
export 'src/domain_packs/co_commerce_domain.dart';
export 'src/domain_packs/co_grocery_domain.dart';
export 'src/domain_packs/co_fake_catalog_item.dart';
export 'src/domain_packs/co_faker_catalog.dart';
export 'src/domain_packs/co_booking_domain.dart';
export 'src/domain_packs/co_fake_booking_slot.dart';
export 'src/domain_packs/co_faker_booking.dart';
export 'src/domain_packs/co_fake_exam_question.dart';
export 'src/domain_packs/co_faker_exam_prep.dart';
export 'src/domain_packs/co_fake_vital_reading.dart';
export 'src/domain_packs/co_dental_domain.dart';
export 'src/domain_packs/co_homecare_domain.dart';
export 'src/domain_packs/co_travel_wallet_domain.dart';
export 'src/domain_packs/co_b2b_trade_domain.dart';
export 'src/domain_packs/co_group_deal_domain.dart';
export 'src/domain_packs/co_fitness_domain.dart';
export 'src/domain_packs/co_space_rental_domain.dart';
export 'src/domain_packs/co_dining_domain.dart';
export 'src/domain_packs/co_daycare_domain.dart';
export 'src/domain_packs/co_exam_prep_domain.dart';
export 'src/domain_packs/co_hrd_domain.dart';
export 'src/domain_packs/co_neighborhood_domain.dart';
export 'src/domain_packs/co_meetup_domain.dart';
export 'src/domain_packs/co_fandom_domain.dart';
export 'src/domain_packs/co_content_domain.dart';
export 'src/domain_packs/co_helpdesk_domain.dart';
export 'src/domain_packs/co_faker_helpdesk.dart';
export 'src/domain_packs/co_campaign_domain.dart';
export 'src/domain_packs/co_workplace_domain.dart';
export 'src/domain_packs/co_brokerage_domain.dart';
export 'src/domain_packs/co_logistics_domain.dart';
export 'src/domain_packs/co_hospitality_domain.dart';
export 'src/korea.dart';
export 'src/modules.dart';
export 'src/random_source.dart';
export 'src/saas.dart';
export 'src/saas_data.dart';
export 'src/saas_ops.dart';
export 'src/signature.dart';
export 'src/schema.dart';
